apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app.kubernetes.io/name: mydeploy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mydeploy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mydeploy
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: default
        persistentVolumeClaim:
          claimName: mypvc
      containers:
      - name: default
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sleep", "9999"]
        volumeMounts:
        - name: default
          mountPath: /mypvc
          readOnly: true
