# Default values for issue-5792-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 8

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""