kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: worker-second-worker
  labels:
    name: worker-second-worker
spec:
  replicas: {{ required ".workers.second_worker is required in values.yaml" .Values.workers.second_worker.replicas}}
